# Site Settings
title: ResumeMVC
url: 'http://marco-evc.github.io/'
#baseurl: '/resumedpc' #change it according to your repository name

#Profile information
name: Marco Vázquez
tagline: Sr. iOS Developer
pic: profile.png  #place a 100x100 picture inside /assets/images/ folder and provide the name of the file below
summary: "Marco es un Ingeniero en Mecatrónica con más de 5 años de experiencia en el desarrollo de aplicaciones móviles principalmente para el sector financiero. Ha participado en todas las fases del desarrollo tales como levantar requerimientos, analisis de información, toma de decisiones e implementación usando teconologías como Swift, Objective-C y SwiftUI bajo un marco de trabajo ágil."

#sidebar links
email: vazquezmarco3@gmail.com
phone: 5529721793
linkedin: marco-emilio-vazquez-calva-174255a1
github: marco-evc
#Update all the sections by editing the files inside _data folder.

# Tracker
analytics: UA-83979019-1

# Build settings
encoding: "utf-8"
compress_html: # - http://jch.penibelst.de/
  clippings: all
  ignore:
    envs: development
